### ISSUE TITLE
another janus problem

### ISSUE THREAD

**Issue by iccanobif** [iccanobif/gikopoi2#329]
Maximum number of publishers (20) already reached PluginError: Maximum number of publishers (20) already reached    at /app/node_modules/janus-videoroom-client/src/plugins/handle.js:155:28    at runMicrotasks (<anonymous>)    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by iccanobif** [comment]
still seems to be a problem (8 instances of this error in the last 48 hours)

**Comment by 2sh** [comment]
Hopefully not an issue anymore, but increasing the number of publishers is probably a good idea anyway
